export const articles = [
  {
    slug: "bel-fitigi-ameliyati",
    title: "Bel Fıtığı Ameliyatı: Mikrocerrahi ile Aynı Gün Yürümek Mümkün",
    img: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200",
    date: "12 Mart 2025",
    readTime: "7 dk okuma",
    category: "Bel Fıtığı",
    desc: "Bel fıtığı ameliyatı artık 1.5 cm'lik kesiden, mikroskop altında uygulanıyor ve hastalar aynı gün yürüyebiliyor. Bu yazıda mikrodiskektominin nasıl yapıldığını, kimlere gerektiğini ve iyileşme sürecini ayrıntıyla anlatıyoruz.",
    intro: `Bacağınıza vuran şiddetli ağrı, geceleri uyandıran siyatik, oturamama… Bel fıtığı yaşayan milyonlarca insan bu tabloya aşinadır. "Ameliyat olmadan geçer mi?" sorusunun cevabı birçok vakada evettir — ancak 6 haftayı aşan, nörolojik hasar gösteren ya da günlük yaşamı felç eden vakalarda mikrocerrahi, hem en güvenli hem de en hızlı çözümü sunar.`,
    sections: [
      { h2: "Bel Fıtığı Neden Oluşur?", content: `Omurlar arasındaki disk yastıkları, yaşlanma, aşırı yük ve ani travmalarla zamanla dejenere olur. Diskin dış tabakası (anulus fibrozus) yırtıldığında içindeki jel kıvamındaki çekirdek (nukleus pulpozus) dışa fırlar ve çevre sinir köküne ya da omurilik kanalına baskı yapar. Bu baskı; siyatik ağrısı, his kaybı ve güçsüzlük olarak kendini gösterir.\n\nEn sık görülen bel fıtığı seviyeleri L4–L5 ve L5–S1'dir. L4–L5 fıtığı ayak bileğini kaldırmayı güçleştirirken, L5–S1 fıtığı topukta kuvvet kaybına yol açar.` },
      { h2: "Bel Fıtığı Ameliyatı — Mikrodiskektomi Nasıl Yapılır?", content: `Genel anestezi altında başlayan operasyonda Prof. Dr. Ermiş, hastanın sırtında fıtığın tam üzerine gelecek biçimde yalnızca 1.5 cm'lik bir kesi yapar. Ameliyat mikroskobu devreye girerek görüş alanını büyütür; bu sayede sinir kökü hassasiyetle korunurken fıtık kütlesi milimetrik dikkatle temizlenir.\n\nOperasyon ortalama 45–60 dakika sürer. Hasta 4–6 saat içinde kalkıp yürür; çoğunlukla ertesi gün taburcu edilir. Masa başı işlere 1–2 haftada, fiziksel işlere ise 4–6 haftada dönüş mümkündür.` },
      { h2: "Bel Fıtığı Ameliyatı Kimlere Gerekir?", content: `Her bel fıtığı ameliyat gerektirmez. Aşağıdaki durumlar cerrahi için güçlü endikasyonlardır:\n\n• Ağrı 6 haftadan uzun sürüyor ve konservatif tedaviye yanıt vermiyorsa\n• Ayak veya bacakta ilerleyen kuvvet kaybı varsa (özellikle düşük ayak)\n• İdrar ya da bağırsak kontrolünde ani güçlük (kauda equina sendromu) — bu durum acil cerrahidir\n• Ağrı kesiciler etkinliğini yitirdi ve yaşam kalitesi ciddi biçimde bozulduysa` },
      { h2: "Ameliyat Sonrası İyileşme Süreci", content: `Mikrocerrahi sonrası siyatik ağrısının büyük bölümü ilk günlerde geriler. Sinirin tam iyileşmesi 3–6 ay sürebilir; bu sürede hafif karıncalanma hissi normal kabul edilir.\n\nİyileşmeyi hızlandırmak için öneriler:\n• İlk 4–6 haftada ağır kaldırmaktan ve öne eğilmekten kaçının\n• Fizyoterapist eşliğinde core (gövde) egzersizlerine başlayın\n• Yürüyüş, en temel ve etkili rehabilitasyon aracıdır — günde 2–3 kez kısa yürüyüşler yapın\n• Sigara iyileşmeyi yavaşlatır; mümkünse bırakın` },
      { h2: "Ameliyat Sonrası Tekrar Fıtık Olur mu?", content: `Her 100 operasyonun yaklaşık 5–8'inde aynı seviyede tekrar fıtık oluşabilir. Bunun önüne geçmek için kilo kontrolü, düzenli core egzersizleri ve doğru kaldırma teknikleri hayati önem taşır. Tekrar fıtık oluştuğunda yeniden mikrodiskektomi veya endoskopik diskektomi başarıyla uygulanabilir.` },
    ],
    tags: ["Bel Fıtığı", "Mikrodiskektomi", "Siyatik", "Lomber Disk", "Omurga Cerrahisi"],
  },
  {
    slug: "skolyoz-belirtileri-tedavisi",
    title: "Skolyoz Belirtileri ve Tedavisi: Erken Teşhis Neden Bu Kadar Önemli?",
    img: "https://images.unsplash.com/photo-1581594549595-35f6edc7b762?q=80&w=1200",
    date: "28 Şubat 2025",
    readTime: "8 dk okuma",
    category: "Skolyoz",
    desc: "Skolyoz, omurganın 10 derecenin üzerinde anormal eğrilmesidir ve çoğunlukla büyüme çağında fark edilir. Erken teşhis, VBT gibi füzyonsuz yöntemlerle ameliyatsız hisse yakın sonuçlar elde etmeyi mümkün kılar.",
    intro: `Okul çağındaki çocuğunuzun sırtına baktığınızda bir omuzun diğerinden yüksek durduğunu, bele ilişkin kıyafetlerin eşit oturmadığını fark ettiniz mi? Bu bulgular skolyozun erken işaretleri olabilir. Türkiye'de her 100 çocuktan 2–3'ünde anlamlı omurga eğriliği saptanmaktadır. İyi haber: erken yakalandığında VBT gibi modern yöntemlerle cerrahi füzyon yapmaksızın etkili tedavi mümkündür.`,
    sections: [
      { h2: "Skolyoz Nedir?", content: `Skolyoz, omurganın öne-arkadan (frontal düzlemde) 10 derecenin üzerinde anormal biçimde sağa ya da sola eğrilmesidir. Eğrilik çoğunlukla S veya C şeklini alır. En yaygın türü olan Adölesan İdiyopatik Skolyoz (AIS), 10–16 yaş arasında, kesin nedeni bilinmeksizin ortaya çıkar. Kızlarda ilerleyen vakaların sıklığı erkeklere göre 8 kat daha fazladır.` },
      { h2: "Skolyoz Belirtileri Nelerdir?", content: `Çoğu skolyoz başlangıçta ağrısız seyreder; bu nedenle aile bireyleri ya da okul taramaları tanıda kritik rol oynar. Dikkat edilmesi gereken bulgular:\n\n• Omuzların eşit yükseklikte durmaması\n• Sırtın bir tarafının diğerinden belirgin kabarık görünmesi (jilet sırtı)\n• Kalçaların dengesiz durması\n• Öne eğilince sırtta asimetri\n• İleri vakalarda kronik sırt-bel ağrısı ve kısa nefes alma` },
      { h2: "VBT (Vertebral Body Tethering) Nedir?", content: `VBT, Türkiye'de uygulanan en yeni skolyoz cerrahi tekniklerinden biridir. Büyüme potansiyeli olan 10–16 yaş hastalarında, Cobb açısı 40–65° arasındayken uygulanır.\n\nToraks kısmına küçük kesilerden girilir (torakoskopik yaklaşım). Eğriliğin iç tarafındaki omurganın yan yüzlerine vidalar yerleştirilir ve vidalar arasına esnek bir bant (tether) gerilir. Hasta büyüdükçe bant, omurgayı kademeli olarak diker.\n\nVBT'nin temel avantajı: füzyon (kaynama) gerektirmez, hareket kabiliyeti tamamen korunur ve hasta çok daha hızlı iyileşir.` },
      { h2: "Skolyozda Korse Ne Zaman Yeterlidir?", content: `Cobb açısı 25–45° arasında ve büyüme devam ediyorsa korse ilerlemeyi yavaşlatabilir. Ancak korse skolyozu düzeltmez; yalnızca eğriliğin artmasını önlemeye çalışır.\n\nKorse kullanımı için koşullar:\n• Büyüme plakaları açık olmalıdır (Risser 0–2)\n• Cobb açısı 25–45° arasında olmalıdır\n• Günde en az 18–23 saat kullanılmalıdır` },
      { h2: "Skolyoz Ameliyatından Sonra Hayat Nasıl?", content: `VBT sonrası hastalar genellikle 3–5 günde taburcu olur. 3–4 haftada okula dönüş mümkündür; 6–9 ayda spora kademeli dönüş sağlanır. Müzik enstrümanı çalmak, yüzmek ve günlük aktiviteler ortalama 3 ayda tamamen normal seyreder.\n\nFüzyon cerrahisinde ise spora dönüş 12–18 ay sürebilir. Her iki yöntemde de düzenli radyolojik takip önerilir.` },
    ],
    tags: ["Skolyoz", "VBT", "Kifoz", "Omurga Eğriliği", "Çocuk Ortopedisi", "Omurga Cerrahisi"],
  },
  {
    slug: "diz-protezi-ameliyati",
    title: "Diz Protezi Ameliyatı: Robotik Cerrahi ile Ertesi Gün Yürümek",
    img: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=1200",
    date: "10 Ocak 2025",
    readTime: "6 dk okuma",
    category: "Eklem Protezi",
    desc: "Diz kireçlenmesinde (osteoartrit) ağrı kesiciler işe yaramıyorsa robotik total diz protezi en kalıcı çözümdür. Hastalar ertesi gün yürüyebilir; modern implantlar 20–25 yıl işlev görür.",
    intro: `Merdiven inerken çekilen o keskin ağrı, geceleri uyandıran sızı, artık kaldırmanın anlamsız geldiği ağrı kesiciler… Diz kireçlenmesinin son evresinde milyonlarca kişinin tanıdığı bu tablo, robotik total diz protezi ile köklü biçimde değişebilir. Modern implantlar ve robotik hassasiyetle gerçekleştirilen bu operasyonda hastaların büyük çoğunluğu ertesi gün yürümeye başlamaktadır.`,
    sections: [
      { h2: "Diz Kireçlenmesi (Osteoartrit) Nedir?", content: `Osteoartrit, diz eklemini örten kıkırdak dokunun zamanla aşınmasıdır. Kıkırdak incelip yok oldukça kemikler birbirine sürtünmeye başlar; bu durum şiddetli ağrı, şişlik ve hareket kısıtlılığına yol açar. 60 yaş üstü nüfusun yaklaşık %30'u klinik osteoartrit belirtileri yaşamaktadır.` },
      { h2: "Robotik Diz Protezi Neden Daha İyi?", content: `Geleneksel diz protezinde cerrah, ameliyat sırasında kemik kesimlerini el aleti ve kılavuzlarla yapar. Robotik sistemde ise:\n\n• Ameliyat öncesi 3 boyutlu kemik modeli hazırlanır\n• İmplant pozisyonu bilgisayarda milimetrik hassasiyetle planlanır\n• Ameliyat sırasında robot, planlanan sınırların dışına çıkılmasını otomatik olarak engeller\n• Bacak ekseni mükemmel biçimde düzeltilir` },
      { h2: "Diz Protezi Ameliyatı Nasıl Gerçekleşir?", content: `Spinal veya genel anestezi altında gerçekleştirilen operasyon ortalama 60–90 dakika sürer. Hasta ameliyat sonrası fizyoterapist eşliğinde ertesi sabah yürür. Taburculuk genellikle 2–3. günde gerçekleşir.` },
      { h2: "Diz Protezi Sonrası Neler Yapılabilir?", content: `Rehabilitasyon tamamlandıktan sonra merdiven inip çıkmak, araba kullanmak, yüzmek, bisiklet sürmek ve yürüyüş yapmak rahatlıkla mümkündür. Modern diz protezlerinde 120–130° fleksiyon açısına ulaşılabilir.` },
      { h2: "Diz Protezi Ömrü Nedir?", content: `Günümüz implantlarının %90–95'i 20–25 yıl sorunsuz çalışmaktadır. Kilo kontrolü, düzenli egzersiz (yüzme, bisiklet) ve yüksek darbeli aktivitelerden kaçınmak protez ömrünü uzatan en önemli faktörlerdir.` },
    ],
    tags: ["Diz Protezi", "Robotik Cerrahi", "Osteoartrit", "Kireçlenme", "Eklem Protezi"],
  },
  {
    slug: "boyun-fitigi-belirtileri",
    title: "Boyun Fıtığı Belirtileri ve Tedavisi: Kola Vuran Ağrıya Son",
    img: "https://images.unsplash.com/photo-1582560469715-d72b220bc0a6?q=80&w=1200",
    date: "5 Kasım 2024",
    readTime: "6 dk okuma",
    category: "Boyun Fıtığı",
    desc: "Boyun fıtığı omuz, kol ve parmaklara yayılan ağrı ile kendini gösterir. ACDF ve yapay disk (TDR) yöntemleriyle küçük bir kesiden kalıcı çözüm mümkündür.",
    intro: `Boyun ağrısı, dünya genelinde bel ağrısından sonra en sık karşılaşılan ikinci kas-iskelet şikâyetidir. Uzun süreli bilgisayar ve telefon kullanımı, ofis hayatı ve hareketsizlik bu riski dramatik biçimde artırıyor.`,
    sections: [
      { h2: "Boyun Fıtığı Neden Olur?", content: `Boyun (servikal) omurlar arasındaki disk yastıkları yaş ilerledikçe su kaybeder ve elastikiyetini yitirir. C5–C6 ve C6–C7 seviyeleri en sık etkilenen bölgelerdir.` },
      { h2: "Boyun Fıtığı Belirtileri Nelerdir?", content: `• C5 kökü: Omuzda ağrı ve deltoid kasında güçsüzlük\n• C6 kökü: Başparmak ve işaret parmağında uyuşukluk\n• C7 kökü: Orta parmakta his kaybı, dirsek ekstansiyonunda güçsüzlük (en sık!)\n• C8 kökü: 4. ve 5. parmakta uyuşukluk, kavrama güçsüzlüğü` },
      { h2: "ACDF Ameliyatı Nedir?", content: `Anterior Servikal Diskektomi ve Füzyon (ACDF), boyun fıtığının cerrahi tedavisinde en yaygın uygulanan yöntemdir. Operasyon 1–1.5 saat sürer, hasta 1–2 günde taburcu edilir ve 2–4 haftada günlük yaşamına döner.` },
      { h2: "Yapay Disk (TDR) ile ACDF Farkı Nedir?", content: `Total Disk Replasmanı'nda (TDR) kafes yerine hareketli yapay disk yerleştirilir; boyun hareketi korunur ve komşu seviyelere binen yük azalır. TDR özellikle tek seviye fıtığı olan, genç ve aktif hastalarda tercih edilir.` },
    ],
    tags: ["Boyun Fıtığı", "Servikal Disk", "ACDF", "Yapay Disk", "Omurga Cerrahisi"],
  },
  {
    slug: "cocuk-ortopedisi-kalca-cikigi",
    title: "Çocuklarda Kalça Çıkığı (GKD): Erken Teşhis Ameliyatı Önler",
    img: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200",
    date: "20 Eylül 2024",
    readTime: "5 dk okuma",
    category: "Çocuk Ortopedisi",
    desc: "Gelişimsel kalça displazisi (GKD), bebeklerde her 100 doğumda 1–3'ünde görülür. İlk 6 ayda teşhis edildiğinde Pavlik bandajıyla %90 üzerinde ameliyatsız başarı elde edilir.",
    intro: `Her yeni doğanın kalçası farklıdır; ancak bazı bebeklerde kalça ekleminin yuvası yetersiz gelişmiş ya da femur başı tamamen yerinden çıkmış olabilir.`,
    sections: [
      { h2: "GKD (Gelişimsel Kalça Displazisi) Nedir?", content: `GKD, femur başının asetabulum içinde tam oturmadığı bir gelişimsel bozukluktur. Her 100 canlı doğumda 1–3 bebekte görülür; kız bebeklerde risk 6 kat daha yüksektir.` },
      { h2: "GKD Belirtileri Nasıl Fark Edilir?", content: `• Bebekte bacak uzunlukları eşit değil\n• Uyluk veya kasık kıvrımları asimetrik\n• Kalçayı açmada direnç ya da "çıt" sesi\n• Yürümeye başlayan çocuklarda topallama` },
      { h2: "GKD Tedavisi Nasıl Yapılır?", content: `0–6 ay: Pavlik bandajı ile %90'ın üzerinde başarı.\n6–18 ay: Kapalı redüksiyon ve spika alçı.\n18 ay ve üzeri: Açık cerrahi redüksiyon gerekebilir.` },
      { h2: "GKD Tedavi Edilmezse Ne Olur?", content: `Tedavi edilmeyen GKD erken yetişkin dönemde ciddi kalça kireçlenmesine ve yürüyüş bozukluğuna yol açar. Bu nedenle erken tarama hayati önem taşır.` },
    ],
    tags: ["Kalça Çıkığı", "GKD", "Çocuk Ortopedisi", "Pavlik Bandajı", "Bebek Kalça Displazisi"],
  },
  {
    slug: "acl-cop-bag-ameliyati",
    title: "Ön Çapraz Bağ (ACL) Ameliyatı: Sporculara Spora Dönüş Rehberi",
    img: "https://images.unsplash.com/photo-1551076805-e18690c5e561?q=80&w=1200",
    date: "3 Ağustos 2024",
    readTime: "7 dk okuma",
    category: "Artroskopik Cerrahi",
    desc: "ACL kopması artroskopik rekonstrüksiyonla tedavi edilir. Doğru greft seçimi ve rehabilitasyon protokolüyle sporcularda 6–9 ayda spora dönüş mümkündür.",
    intro: `Futbol, basketbol ya da kayak yaparken ani bir manevra sırasında dizinizde duyduğunuz "çat" sesi ve hemen ardından gelen şişlik — ön çapraz bağ (ACL) kopmasının klasik tablosudur.`,
    sections: [
      { h2: "Ön Çapraz Bağ (ACL) Nedir ve Neden Kopar?", content: `ACL, diz eklemini ön-arka yönde stabilize eden güçlü bir bağdır. Ani yön değiştirme, durma, atlama ve diz üzerine düşme gibi mekanizmalarla yırtılır.` },
      { h2: "ACL Kopması Nasıl Anlaşılır?", content: `• Yaralanma sırasında "çat" sesi\n• Dakikalar içinde gelişen belirgin şişlik\n• Diz boşalması hissi ve instabilite\n• Yürüyüşte güçlük` },
      { h2: "ACL Rekonstrüksiyonu Nasıl Yapılır?", content: `Kopan bağ, hamstring veya patellar tendon greftiyle artroskopik teknikle yeniden inşa edilir. Operasyon yaklaşık 45–60 dakika sürer; hasta aynı gün ya da ertesi gün taburcu edilir.` },
      { h2: "ACL Ameliyatı Sonrası Spora Ne Zaman Dönülür?", content: `Ortalama 6–9 ayda tam spora dönüş sağlanır. Spora dönüş için diz gücünün sağlıklı tarafa göre %90 oranına ulaşması gerekir.` },
    ],
    tags: ["ACL", "Ön Çapraz Bağ", "Diz Ameliyatı", "Artroskopi", "Menisküs", "Spor Cerrahisi"],
  },
];