export const TREATMENTS_DATA = [
  {
    slug: "skolyoz-kifoz-cerrahisi",
    title: "Skolyoz & Kifoz Cerrahisi",
    img: "/images/skolyoz-kifoz.png",
    category: "Omurga Cerrahisi",
    stats: [{ label: "VBT Cobb açısı", val: "40–65°" }, { label: "Hastane süresi", val: "3–5 gün" }, { label: "Düzeltme başarısı", val: "%85+" }],
    desc: [
      "Skolyoz, omurganın öne-arkadan bakıldığında sağa ya da sola 10 derecenin üzerinde anormal biçimde eğrilmesidir. Kifoz ise omurganın öne doğru aşırı kamburlaşmasıdır; halk arasında \"kambur sırt\" olarak bilinir. Her iki durum da erken teşhis edilmediğinde zamanla ilerleyerek akciğer kapasitesini azaltır, kronik ağrıya ve ciddi hareket kısıtlılığına yol açar.",
      "Skolyoz en sık 10–16 yaş arasındaki büyüme çağı çocuklarında (adölesan idiyopatik skolyoz) görülmekle birlikte yetişkinlerde de dejeneratif form olarak ortaya çıkabilir. Türkiye'de her 100 çocuktan 2–3'ünde anlamlı omurga eğriliği saptanmaktadır.",
      "Prof. Dr. M. Nurullah Ermiş, skolyoz ve kifoz cerrahisinde Vertebral Body Tethering (VBT) dahil tüm güncel minimal invaziv ve açık cerrahi teknikleri uygulamaktadır. Özellikle büyüme potansiyeli olan adölesan hastalarda VBT, omurgayı füzyon yapmaksızın kademeli olarak düzelten \"büyüme dostu\" bir yöntemdir.",
    ],
    symptoms: [
      "Sırtta veya belde gözle görülür asimetri ve eğrilik",
      "Omuzların ya da kalçaların farklı yüksekliklerde durması",
      "Öne eğilince sırtta belirgin kabarma (jilet sırtı)",
      "Uzun süre ayakta durmakta ve yürümekte güçlük",
      "İlerleyen eğrilikle birlikte sırt ve bel ağrısı",
      "Ağır vakalarda nefes darlığı ve çabuk yorulma",
    ],
    treatment: [
      { baslik: "VBT (Vertebral Body Tethering)", icerik: "Büyüme potansiyeli olan 10–16 yaş hastalarında, Cobb açısı 40–65° arasında iken uygulanır. Torakoskopik (kapalı) yöntemle vertebralara vidalar yerleştirilir ve esnek bir bant gerilir. Hasta büyüdükçe bant omurgayı kademeli olarak düzeltir; füzyon gerekmez, hareket kabiliyeti tamamen korunur." },
      { baslik: "Posterior Spinal Füzyon (PSF)", icerik: "Büyümesini tamamlamış veya 65° üzeri eğrilikli hastalarda uygulanır. Nöromonitör eşliğinde 3 boyutlu navigasyon ile vida-çubuk sistemi yerleştirilerek kalıcı düzeltme sağlanır. Ameliyat sonrası hastalar genellikle 3–5 günde taburcu olur ve 3–6 ay içinde normal yaşamına döner." },
    ],
    faq: [
      { s: "Skolyoz ameliyatı olmadan geçer mi?", c: "25° altındaki hafif eğrilikler büyüme tamamlandıktan sonra duraksayabilir. 25–45° arası vakalarda korse ilerlemeyi yavaşlatır. Ancak 45° üzerindeki eğrilikler büyümeyle hızlanmaya devam ettiğinden cerrahi tek kalıcı çözümdür." },
      { s: "Skolyoz ameliyatından sonra spora dönülebilir mi?", c: "VBT sonrası 6–9 ayda, füzyon sonrası ise 12–18 ayda kademeli spora dönüş sağlanır. Yüzme ve bisiklet en erken başlanabilen sporlardır." },
      { s: "Skolyoz ameliyatı kaç yaşında yapılır?", c: "VBT genellikle büyüme plakaları açık olan 10–16 yaş arasında uygulanır. Füzyon ameliyatı her yaşta yapılabilir; yetişkin skolyozunda da etkili sonuçlar elde edilmektedir." },
    ],
  },
  {
    slug: "bel-fitigi-tedavisi",
    title: "Bel Fıtığı Tedavisi",
    img: "/images/bel-fitigi.png",
    category: "Omurga Cerrahisi",
    stats: [{ label: "Cerrahi kesi boyutu", val: "1.5 cm" }, { label: "Operasyon süresi", val: "45–60 dk" }, { label: "Yürüme zamanı", val: "Aynı gün" }],
    desc: [
      "Bel fıtığı (lomber disk hernisi), omurlar arasındaki disk yastıklarının dışa taşarak çevre sinir köklerine ya da omurilik kanalına baskı yapmasıyla oluşur. En sık L4–L5 ve L5–S1 seviyelerinde görülür. Bacağa vuran şiddetli ağrı (siyatik), uyuşukluk ve kas güçsüzlüğü en tipik belirtileridir.",
      "Türkiye'de aktif nüfusun yaklaşık %10'u yaşamlarının bir döneminde anlamlı bel fıtığı ağrısı yaşamaktadır. Uzun süreli oturma, yanlış kaldırma teknikleri ve hareketsiz yaşam en önemli risk faktörleridir.",
      "Prof. Dr. Ermiş, bel fıtığı ameliyatlarını ameliyat mikroskobu altında yalnızca 1.5 cm'lik kesiden uygulayarak hastanın aynı gün ayağa kalkmasını ve çoğunlukla ertesi gün taburcu olmasını sağlamaktadır.",
    ],
    symptoms: [
      "Belden kalça, uyluk, diz ve ayak tabanına yayılan siyatik ağrısı",
      "Ayak veya parmaklarda his kaybı ve uyuşukluk",
      "Ayak bileğini yukarı kaldıramama (düşük ayak — acil cerrahi gerektirir)",
      "Uzun süre oturamama, araba kullanmada güçlük",
      "Geceleri uyandıran ağrı nöbetleri",
      "İdrar veya bağırsak kontrolünde ani güçlük (kauda equina — acil!)",
    ],
    treatment: [
      { baslik: "Mikrodiskektomi", icerik: "Genel anestezi altında yaklaşık 45–60 dakikada tamamlanan operasyonda, yalnızca 1.5 cm'lik kesi yoluyla ameliyat mikroskobu altında sinire baskı yapan disk parçası hassasiyetle çıkarılır. Sağlıklı disk dokusu ve kaslar korunur; hasta ameliyat günü 4–6 saat içinde yürür, ertesi gün taburcu edilir." },
      { baslik: "Endoskopik Diskektomi", icerik: "Geleneksel mikrocerrahiden bile daha küçük kesilerle (7 mm) endoskop eşliğinde uygulanan bu yöntemde kas hasarı minimuma iner. Özellikle obez hastalar ve tekrar ameliyat gerektiren olgularda avantaj sağlar. Hasta aynı gün taburcu edilebilir." },
      { baslik: "Ne zaman ameliyat gerekli?", icerik: "Belirtiler 6 haftadan uzun sürüyorsa, günlük yaşamı kısıtlayan ağrı varsa ya da nörolojik tablo (kuvvet kaybı, his bozukluğu) gelişiyorsa cerrahi öncelikli seçenektir. 6 haftadan kısa, nörolojik bulgu yoksa fizik tedavi ve ağrı yönetimiyle takip önerilir." },
    ],
    faq: [
      { s: "Bel fıtığı ameliyat olmadan iyileşir mi?", c: "Hafif vakaların %70–80'i 6–12 haftada kendiliğinden iyileşebilir. Ancak kauda equina sendromu veya ilerleyen sinir hasarı durumunda acil cerrahi zorunludur." },
      { s: "Bel fıtığı ameliyatı sonrası ne zaman işe dönülür?", c: "Masa başı işlerde 1–2 hafta, fiziksel işlerde 4–6 hafta sonra iş hayatına dönüş mümkündür. Ağır kaldırmaktan en az 3 ay kaçınılmalıdır." },
      { s: "Bel fıtığı ameliyatı sonrası tekrar fıtık oluşur mu?", c: "Her 100 hastanın yaklaşık 5–8'inde aynı seviyede tekrar fıtık görülebilir. Kilo kontrolü, core egzersizleri ve doğru kaldırma teknikleri riski belirgin azaltır." },
      { s: "Bel fıtığı ağrısı ne zaman geçer?", c: "Mikrocerrahi sonrası siyatik ağrısının büyük bölümü ilk günlerde geriler. Sinirin tam iyileşmesi 3–6 ay sürebilir." },
    ],
  },
  {
    slug: "boyun-fitigi-cerrahisi",
    title: "Boyun Fıtığı Cerrahisi",
    img: "/images/boyun-fitigi.png",
    category: "Omurga Cerrahisi",
    stats: [{ label: "Cerrahi kesi", val: "~3 cm" }, { label: "Hastane süresi", val: "1–2 gün" }, { label: "İşe dönüş", val: "2–4 hafta" }],
    desc: [
      "Boyun fıtığı (servikal disk hernisi), boyun omurları arasındaki disk yastıklarının taşarak kola giden sinir köklerine ya da doğrudan omuriliğe baskı yapmasıyla oluşur. En sık C5–C6 ve C6–C7 seviyeleri etkilenir. Kolda ağrı, uyuşukluk ve güçsüzlük tipik belirtilerdir.",
      "Uzun süreli bilgisayar kullanımı, öne eğik baş pozisyonu ve hareketsiz ofis hayatı boyun fıtığı riskini artırır. Omurilik basısı yapan ileri vakalarda (servikal miyelopati) yürüme bozukluğu ve denge sorunları ortaya çıkabilir; bu durum acil değerlendirme gerektirir.",
      "Prof. Dr. Ermiş, boyun fıtığı cerrahisini boynun ön tarafından yapılan estetik bir kesiyle, ameliyat mikroskobu altında uygulayarak sorunlu diski temizlemekte ve yerine titanyum kafes (cage) ya da yapay disk yerleştirmektedir.",
    ],
    symptoms: [
      "Omuzdan kola, ön kola ve parmak uçlarına yayılan ağrı",
      "Parmaklarda karıncalanma, uyuşukluk ve kavrama güçsüzlüğü",
      "Düğme ilikleme veya kalem tutma gibi ince hareketlerde güçlük",
      "Boyun hareketlerinde ciddi kısıtlılık ve ense sertliği",
      "Bacaklarda denge sorunu veya yürüme güçlüğü (omurilik basısı işareti)",
    ],
    treatment: [
      { baslik: "ACDF — Anterior Servikal Diskektomi ve Füzyon", icerik: "Boynun ön-yan tarafından yaklaşık 3 cm'lik estetik kesiyle, ameliyat mikroskobu altında sorunlu disk tamamen çıkarılır. Yerine titanyum veya PEEK kafes (cage) yerleştirilerek disk yüksekliği korunur ve kaynak (füzyon) sağlanır. En sık uygulanan ve klinik sonuçları kanıtlanmış yöntemdir." },
      { baslik: "TDR — Total Disk Replasmanı (Yapay Disk)", icerik: "Özellikle tek seviye fıtıklarda ve aktif, güncel hastalarda tercih edilir. Diskektomi sonrası kafes yerine hareketli yapay disk yerleştirilerek boyun hareketi korunur. Komşu seviyelere binen yük azalır; uzun vadede ek seviye sorunları riski düşer." },
    ],
    faq: [
      { s: "Boyun fıtığı egzersizle geçer mi?", c: "Hafif vakalarda boyun egzersizleri ve fizik tedavi ağrıyı azaltabilir. Ancak kola yayılan ağrı, güçsüzlük veya omurilik basısı bulguları varsa egzersiz tek başına yeterli olmaz ve uzman değerlendirmesi gereklidir." },
      { s: "Boyun ameliyatı tehlikeli midir?", c: "Deneyimli ellerde ACDF komplikasyon oranı çok düşüktür. Ses kısıklığı %2–5 oranında ve geçici olarak görülebilir." },
      { s: "Kafes mi yapay disk mi daha iyi?", c: "Karar; hastanın yaşına, aktivite düzeyine, etkilenen seviye sayısına ve kemik kalitesine göre verilir. Her iki yöntemin de kanıtlanmış uzun dönem sonuçları mevcuttur." },
      { s: "Boyun ameliyatı sonrası boyunluk takılır mı?", c: "Ağır olgularda 2–4 hafta, hafif olgularda ise yalnızca birkaç gün boyunluk önerilir. Hareketsizlik süresini uzatmamak iyileşmeyi hızlandırır." },
    ],
  },
  {
    slug: "diz-kalca-protezi",
    title: "Diz & Kalça Protezi",
    img: "/images/diz-kalca-protezi.png",
    category: "Eklem Cerrahisi",
    stats: [{ label: "Yürüme zamanı", val: "Ertesi gün" }, { label: "Taburculuk", val: "2–3. gün" }, { label: "Protez ömrü", val: "20–25 yıl" }],
    desc: [
      "Diz ve kalça protezi, ileri evre kireçlenme (osteoartrit) veya romatoid artrit nedeniyle tahrip olmuş eklem yüzeylerinin biyouyumlu metal ve plastik implantlarla değiştirilmesi işlemidir. Ameliyat sonrası hastaların büyük çoğunluğu ağrısız bir hayata kavuşmakta ve ertesi gün yürümeye başlamaktadır.",
      "Son yıllarda robotik cerrahi ve bilgisayar destekli navigasyon sistemlerinin kullanıma girmesiyle implant yerleşim hassasiyeti artmış, bacak ekseni uyumu iyileşmiş ve uzun dönem protez ömrü uzamıştır.",
      "Prof. Dr. Ermiş, hem robotik destekli hem de gelişmiş navigasyon sistemleri eşliğinde total diz ve kalça protezi operasyonları gerçekleştirmektedir. Kalça protezinde minimal invaziv ön yaklaşım (anterior approach) uygulandığında kaslar kesilmez; iyileşme hızlanır ve çıkık riski azalır.",
    ],
    symptoms: [
      "Merdiven inip çıkmada ve uzun yürüyüşlerde dayanılmaz ağrı",
      "Eklemin sabah sertleşmesi ve ilk adımlarda tutukluk",
      "Eklem hareket açıklığında belirgin azalma",
      "Geceleri uyandıran kronik ağrı",
      "Ağrı kesicilerin artık yeterince işe yaramaması",
      "Bastonla yürüme ihtiyacı ve günlük yaşamda ciddi kısıtlılık",
    ],
    treatment: [
      { baslik: "Robotik Destekli Total Diz Protezi", icerik: "Ameliyat öncesi hazırlanan 3 boyutlu kemik modeli üzerinde implant pozisyonu milimetrik hassasiyetle planlanır. Ameliyat sırasında robot, belirlenen sınırlar dışına çıkılmasını engelleyerek bacak ekseninin mükemmel biçimde düzeltilmesini sağlar. Geleneksel tekniğe kıyasla implant hizalama hatası belirgin azalır." },
      { baslik: "Total Kalça Protezi (Anterior Yaklaşım)", icerik: "Minimal invaziv ön yaklaşımda kaslar kesilmez, yalnızca aralarından geçilir. Bu sayede ameliyat sonrası ağrı azalır, çıkık riski düşer ve hasta ertesi gün yürümeye başlar. Asetabulum (kase) ve femur başı değiştirilerek tam hareket açıklığı yeniden sağlanır." },
    ],
    faq: [
      { s: "Diz protezi ömrü ne kadar?", c: "Modern implantların %90–95'i 20–25 yıl sorunsuz çalışmaktadır. Aşırı kilo, yüksek darbeli sporlar ve sigara implant ömrünü olumsuz etkiler." },
      { s: "Diz protezi sonrası merdiven çıkılabilir mi?", c: "Evet. Rehabilitasyon tamamlandıktan sonra merdiven inip çıkmak, araba kullanmak ve günlük yaşam aktivitelerinin tamamı mümkündür." },
      { s: "Kalça protezi çıkar mı?", c: "Anterior yaklaşım ve doğru implant seçimiyle çıkık riski %1'in altına iner. İlk 6 haftada önerilen pozisyon kısıtlamalarına uymak bu riski daha da azaltır." },
      { s: "Kaç yaşında protez ameliyatı yapılır?", c: "Yaştan çok eklemdeki hasarın derece ve yaşam kalitesine etkisi belirleyicidir. 50'li yaşlardan itibaren yapılabilmekle birlikte, her hasta kendi koşullarında değerlendirilir." },
    ],
  },
  {
    slug: "cocuk-ortopedisi",
    title: "Çocuk Ortopedisi",
    img: "/images/cocuk-ortopedisi.png",
    category: "Çocuk Ortopedisi",
    stats: [{ label: "GKD erken başarı", val: "%95" }, { label: "Boy uzatma hızı", val: "1 mm/gün" }, { label: "Tedavi yaş aralığı", val: "0–18 yaş" }],
    desc: [
      "Çocuk ortopedisi, kemik-iskelet sisteminin doğumsal veya gelişimsel bozukluklarını inceleyen ve tedavi eden özel bir uzmanlık alanıdır. Erken tanı ve uygun müdahale, çocukların ilerleyen yaşlarda sağlıklı ve aktif bir yaşam sürmesi açısından kritik öneme sahiptir.",
      "Gelişimsel Kalça Displazisi (GKD), çarpık ayak (pes ekinovarus), omurga eğriliği, büyüme bozuklukları ve doğumsal kemik deformiteleri çocuk ortopedisinin başlıca tedavi alanlarını oluşturmaktadır.",
      "Prof. Dr. Ermiş'in çocuk ortopedisi pratiği; GKD, çarpık ayak (Ponseti yöntemi), büyüme çağı skolyozu, boy uzatma cerrahisi (İlizarov, Taylor Spatial Frame, PRECICE çivi) ve çocukluk çağı kırık tedavisini kapsamaktadır.",
    ],
    symptoms: [
      "Bebekte bacak kıvrımlarında asimetri veya bacak kısalığı",
      "Çocuğun yürüyüşünde topallama ya da geniş adımlı yürüyüş",
      "Ayakların içe veya dışa dönük durması",
      "Bacaklarda eşitsiz uzunluk",
      "Omurga eğriliği (özellikle ergenlikte hız kazanan skolyoz)",
      "Boy gelişiminde belirgin yavaşlama veya duraksama",
    ],
    treatment: [
      { baslik: "Gelişimsel Kalça Displazisi (GKD)", icerik: "0–6 aylık bebeklerde Pavlik bandajı ile %90'ın üzerinde başarı elde edilir. 6–18 aylık dönemde kapalı redüksiyon ve spika alçı uygulanır. 18 ay üzerinde ise açık cerrahi redüksiyon gereklidir. Erken tanı tedaviyi dramatik biçimde kolaylaştırır." },
      { baslik: "Çarpık Ayak — Ponseti Yöntemi", icerik: "Doğumdan itibaren uygulanan seri alçılama ile ayak kademeli olarak düzgün pozisyona getirilir. Ardından minimal cerrahi (perkutan Aşil tendonu uzatma) ve özel ortez kullanımı sürdürülür. Vakaların %90'ından fazlası ameliyatsız tedavi edilebilir." },
      { baslik: "Boy Uzatma Cerrahisi", icerik: "İlizarov veya Taylor Spatial Frame (TSF) eksternal fiksatör ya da PRECICE manyetik çivi ile kontrollü kemik uzatması sağlanır. Uzatma hızı günde 1 mm olup her 1 cm uzatma için yaklaşık 2 ay hesaplanır." },
    ],
    faq: [
      { s: "Kalça çıkığı nasıl anlaşılır?", c: "Doğumdan sonraki ilk 4–6 hafta içinde kalça ultrasonografisi önerilir. Asimetrik bacak kıvrımları, bir bacağın daha kısa görünmesi veya kalçayı açmada direnç muayenede fark edilebilir." },
      { s: "Çarpık ayak ameliyatsız tedavi edilebilir mi?", c: "Ponseti yöntemi uygulandığında vakaların %90'ında ameliyatsız başarı elde edilir. Yalnızca Aşil tendonu uzatması küçük bir prosedür olarak gerekebilir." },
      { s: "Boy uzatma ameliyatı ne kadar sürer?", c: "Her 1 cm için yaklaşık 2 ay (1 ay uzatma + 1 ay konsolidasyon) hesaplanır." },
      { s: "Çocuklarda skolyoz ne zaman ameliyat gerektirir?", c: "Cobb açısı 45° üzerine çıktığında, büyüme devam ediyorsa ve korse yetersiz kalıyorsa cerrahi önerilir. VBT ile büyüme çağında füzyonsuz düzeltme mümkündür." },
    ],
  },
  {
    slug: "artroskopik-cerrahi",
    title: "Artroskopik Cerrahi",
    img: "/images/artroskopik-cerrahi.png",
    category: "Artroskopik Cerrahi",
    stats: [{ label: "Kesi sayısı", val: "2 adet" }, { label: "Hastane süresi", val: "1–2 gün" }, { label: "ACL'de spora dönüş", val: "6–9 ay" }],
    desc: [
      "Artroskopi, eklem içine milimetrik kesilerden yerleştirilen kamera ve cerrahi aletler aracılığıyla hem tanı hem de tedavi amacıyla uygulanan minimal invaziv bir yöntemdir. Diz, omuz, kalça ve dirsek eklemlerinde uygulanabilen artroskopi; açık cerrahiye kıyasla çok daha kısa iyileşme süresi, daha az ağrı ve neredeyse görünmez kesi izi avantajı sunar.",
      "Menisküs yırtıkları ve ön çapraz bağ (ACL) kopmaları artroskopinin en sık kullanıldığı durumlardır. Sporcularda ve aktif bireylerde spor hasarları sonrası uygulanan artroskopik cerrahi, büyük çoğunluğunun eski performansına dönmesini sağlamaktadır.",
    ],
    symptoms: [
      "Diz içinde ani tıklama, kilitlenme veya boşalma hissi",
      "Yürürken, merdivenlerden inerken dize keskin ağrı",
      "Spor sırasında dizde güvensizlik ve instabilite",
      "Omuzda takılma, sıkışma ve kol kaldırmada ağrı",
      "Travma sonrası hızla gelişen eklem şişliği",
    ],
    treatment: [
      { baslik: "Menisküs Cerrahisi (Tamirat veya Parsiyel Çıkarma)", icerik: "Yırtığın şekli ve yerine göre menisküs dokusu ya dikilir (tamirat) ya da yırtık parça çıkarılır (parsiyel menisektomi). Tamirat öncelikli seçenektir; çünkü menisküs kıkırdağı korur ve ilerleyen kireçlenmeyi önler." },
      { baslik: "Ön Çapraz Bağ (ACL) Rekonstrüksiyonu", icerik: "Kopan bağ, hamstring tendonu veya patellar tendondan alınan greft ile artroskopik teknikle yeniden oluşturulur. Doğru rehabilitasyon protokolü ile sporcularda 6–9 ayda spora dönüş sağlanır." },
      { baslik: "Omuz Artroskopisi", icerik: "Rotator manşet yırtıkları, SLAP lezyonları ve tekrarlayan omuz çıkıklarında artroskopik tamirat ve stabilizasyon uygulanır. Açık cerrahiye kıyasla iyileşme süreci çok daha hızlıdır." },
    ],
    faq: [
      { s: "Menisküs ameliyatı olmadan iyileşir mi?", c: "Küçük, periferik yırtıklar kendiligününden iyileşebilir. Ancak kilitlenme yapan, ağrıyı sürdüren ve hareket açıklığını kısıtlayan yırtıklar artroskopik tedaviden fayda görür." },
      { s: "Çapraz bağ ameliyatı sonrası futbol oynanabilir mi?", c: "Evet. Uygun rehabilitasyon ve spesifik dönüş testleri tamamlandıktan sonra çoğu sporcu eski performansına ulaşabilir." },
      { s: "Menisküs ameliyatı sonrası ne zaman yürünür?", c: "Tamirat yapıldıysa 4–6 hafta koltuk değneği kullanılır. Parsiyel çıkarmada ise hasta genellikle ertesi gün tam yük verebilir." },
      { s: "Artroskopi genel anestezi mi?", c: "Çoğunlukla spinal veya genel anestezi altında yapılır. Küçük prosedürlerde lokal anestezi ve sedasyon da yeterli olabilir." },
    ],
  },
];
